spring:
  application:
    name: podo

  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: update      # 개발 단계: 테이블 자동 생성/수정
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8080